### ISSUE TITLE
跑不起来,运行报错

### ISSUE THREAD

**Issue by LiuYimin** [easemob/webim-vue-demo#125]
Node 16.2.0
npm install正常
npm run dev后报错

 ERROR  TypeError: validate is not a function
TypeError: validate is not a function
    at new Server (/Users/xxxx/Develop/xxxxxx/xuri-vue3/node_modules/webpack-dev-server/lib/Server.js:231:5)
    at serve (/Users/xxxxx/Develop/xxxxxx/xuri-vue3/node_modules/@vue/cli-service/lib/commands/serve.js:194:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by myZhangDong** [comment]
拉的哪个分支？可以用 vue3 或者 dev-4.0分支

**Comment by LiuYimin** [comment]
> 拉的哪个分支？可以用 vue3 或者 dev-4.0分支

谢谢,我换成vue3分支就OK了,之前拉的是master.

**Comment by LiuYimin** [comment]
> 拉的哪个分支？可以用 vue3 或者 dev-4.0分支

谢谢,我换成vue3分支就OK了,之前拉的是master.
